[22-May-22 15:30:38 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 16:29:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: timed out
[22-May-22 16:29:52 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: timed out
[22-May-22 16:30:02 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: timed out
[22-May-22 16:56:28 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:29 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:30 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:31 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:32 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:32 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:32 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:33 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:34 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:35 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:35 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:35 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:36 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:38 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:38 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:41 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[22-May-22 16:56:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 16:56:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[22-May-22 17:24:46 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 17:24:47 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 17:32:30 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 17:32:30 - INFO] - root - ### Processing: Venom client ###
[22-May-22 17:32:30 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 17:32:40 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:32:45 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:32:46 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 17:40:09 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 17:40:09 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 17:40:13 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 17:40:13 - INFO] - root - ### Processing: Venom client ###
[22-May-22 17:40:13 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 17:40:24 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:40:28 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:40:29 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 17:46:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 17:46:00 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 17:48:48 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 17:48:48 - INFO] - root - ### Processing: Venom client ###
[22-May-22 17:48:48 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 17:48:58 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:49:01 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:49:01 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 17:58:32 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 17:58:32 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 17:58:38 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 17:58:38 - INFO] - root - ### Processing: Venom client ###
[22-May-22 17:58:38 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 17:58:48 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:58:52 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 17:58:53 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 17:59:10 - ERROR] - pyrogram.dispatcher - Message.__init__() missing 1 required keyword-only argument: 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\Apps\Python\Python310\lib\site-packages\pyromod\listen\listen.py", line 93, in resolve_listener
    await self.user_callback(client, message, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__()
TypeError: Message.__init__() missing 1 required keyword-only argument: 'id'
[22-May-22 18:00:02 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:00:03 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:00:08 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:00:08 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:00:08 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:00:12 - ERROR] - asyncio - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Apps\Python\Python310\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[22-May-22 18:00:19 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:00:23 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:00:23 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:00:35 - ERROR] - pyrogram.dispatcher - Message.__init__() missing 1 required keyword-only argument: 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__()
TypeError: Message.__init__() missing 1 required keyword-only argument: 'id'
[22-May-22 18:01:08 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:01:09 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:01:15 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:01:15 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:01:15 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:01:26 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:01:29 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:01:29 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:01:37 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(id=rm)
TypeError: MyMessage.__init__() got an unexpected keyword argument 'id'
[22-May-22 18:03:15 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:03:15 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:03:20 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:03:20 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:03:20 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:03:32 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:03:35 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:03:36 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:03:42 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(rm)
TypeError: MyMessage.__init__() takes 1 positional argument but 2 were given
[22-May-22 18:04:40 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:04:41 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:04:45 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:04:45 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:04:45 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:04:54 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:04:58 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:04:58 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:05:04 - ERROR] - pyrogram.dispatcher - Message.__init__() missing 1 required keyword-only argument: 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage()
  File "D:\USERGE-X\VenomX\venom\core\types\message.py", line 30, in __init__
    super().__init__()
TypeError: Message.__init__() missing 1 required keyword-only argument: 'id'
[22-May-22 18:05:51 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:05:52 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:05:56 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:05:56 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:05:56 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:06:05 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:06:09 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:06:10 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:06:14 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() got an unexpected keyword argument 'id'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(id=rm)
TypeError: MyMessage.__init__() got an unexpected keyword argument 'id'
[22-May-22 18:06:34 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:06:35 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:06:38 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:06:38 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:06:38 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:06:51 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:06:57 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:06:58 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[22-May-22 18:07:02 - ERROR] - pyrogram.dispatcher - MyMessage.__init__() got multiple values for argument 'self'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\core\decorators\on_triggers.py", line 53, in template
    new_message = MyMessage(self=rm)
TypeError: MyMessage.__init__() got multiple values for argument 'self'
[22-May-22 18:07:47 - INFO] - root - Stop signal received (SIGINT). Exiting...
[22-May-22 18:07:48 - INFO] - venom.core.client - ### Stopping bot ###
[22-May-22 18:07:53 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[22-May-22 18:07:53 - INFO] - root - ### Processing: Venom client ###
[22-May-22 18:07:53 - INFO] - venom.core.client - ### Starting bot ###
[22-May-22 18:08:03 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:08:09 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[22-May-22 18:08:09 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
