[23-May-22 13:40:50 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 151, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 13:42:01 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:42:01 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:42:05 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:42:05 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:42:05 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:42:38 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:42:41 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:42:41 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:43:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: timed out
[23-May-22 13:43:37 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:38 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:39 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:40 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[23-May-22 13:43:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:40 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[23-May-22 13:43:40 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:41 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:42 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:43 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:43 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[23-May-22 13:43:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:43:44 - WARNING] - pyrogram.connection.connection - Connection failed! Trying again...
[23-May-22 13:43:44 - WARNING] - pyrogram.connection.connection - Unable to connect due to network issues: [WinError 10065] A socket operation was attempted to an unreachable host
[23-May-22 13:56:04 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:56:04 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:56:18 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:56:18 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:56:18 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:56:27 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:56:28 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:56:29 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:56:57 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 148, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 13:57:00 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 13:57:00 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 13:57:19 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 13:57:19 - INFO] - root - ### Processing: Venom client ###
[23-May-22 13:57:19 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 13:57:28 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:57:30 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 13:57:30 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 13:57:56 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 145, in alive_media_inline
    await i_q.answer(results=results, cache_time=1)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 14:00:37 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 14:00:37 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 14:00:49 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 14:00:49 - INFO] - root - ### Processing: Venom client ###
[23-May-22 14:00:49 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 14:01:02 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 14:01:04 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 14:01:04 - INFO] - venom.plugins - The plugins' list: ['essents.mark_read', 'essents.telegraph', 'fun.alive', 'help', 'inline_queries', 'test.test', 'tools.executor', 'tools.json', 'tools.logs', 'tools.ping', 'tools.startup', 'tools.sudo']
[23-May-22 14:01:09 - ERROR] - pyrogram.dispatcher - 'NoneType' object has no attribute 'write'
Traceback (most recent call last):
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "D:\USERGE-X\VenomX\venom\plugins\fun\alive.py", line 145, in alive_media_inline
    await i_q.answer(results=results)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\types\inline_mode\inline_query.py", line 172, in answer
    return await self._client.answer_inline_query(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\bots\answer_inline_query.py", line 97, in answer_inline_query
    return await self.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\methods\advanced\invoke.py", line 77, in invoke
    r = await self.session.invoke(
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 360, in invoke
    return await self.send(query, timeout=timeout)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\session.py", line 291, in send
    message = self.msg_factory(data)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\session\internals\msg_factory.py", line 37, in __call__
    len(body)
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\tl_object.py", line 79, in __len__
    return len(self.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\functions\messages\set_inline_bot_results.py", line 98, in write
    b.write(Vector(self.results))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_result.py", line 117, in write
    b.write(self.send_message.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\input_bot_inline_message_media_auto.py", line 84, in write
    b.write(self.reply_markup.write())
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\reply_inline_markup.py", line 66, in write
    b.write(Vector(self.rows))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\types\keyboard_button_row.py", line 66, in write
    b.write(Vector(self.buttons))
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in __new__
    + [cast(bytes, t(i)) if t else i.write() for i in value]
  File "D:\Apps\Python\Python310\lib\site-packages\pyrogram\raw\core\primitives\vector.py", line 58, in <listcomp>
    + [cast(bytes, t(i)) if t else i.write() for i in value]
AttributeError: 'NoneType' object has no attribute 'write'
[23-May-22 14:01:12 - INFO] - root - Stop signal received (SIGINT). Exiting...
[23-May-22 14:01:13 - INFO] - venom.core.client - ### Stopping bot ###
[23-May-22 14:02:00 - INFO] - venom.core.database - ### VenomX Database Not Found => Creating New Database... ###
[23-May-22 14:02:00 - INFO] - root - ### Processing: Venom client ###
[23-May-22 14:02:00 - INFO] - venom.core.client - ### Starting bot ###
[23-May-22 14:02:08 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
[23-May-22 14:02:10 - WARNING] - pyrogram.client - [VenomX] No plugin loaded from "venom"
